Feature/shunsuke/items display
yuya-ishikawa-qa/hakkutsu pull request #13
Opened 2020-07-23 09:33 UTC by shunsuke-katsuyama

商品の一覧表示と並び替え機能の実装完了しました。

コードレビューをお願いします。

こちらも店舗の一覧表示と同じく、画像のサイズがまばらになっていますので、後ほど修正いたします。

以上、よろしくお願いします。

2020-07-24 15:22 UTC, ryota100 approved these changes
お疲れ様です。
商品一覧機能と並び替え機能確認しました。
商品の画像は、gitのpushで送れない場所だったのか、確認はできないようでした。
他も大丈夫かと思います。
マージはせずにとりあえず承認だけすることにします。よろしくお願いします。

2020-07-24 22:33 UTC, shunsuke-katsuyama commented
> お疲れ様です。
> 商品一覧機能と並び替え機能確認しました。
> 商品の画像は、gitのpushで送れない場所だったのか、確認はできないようでした。
> 他も大丈夫かと思います。
> マージはせずにとりあえず承認だけすることにします。よろしくお願いします。

コメントありがとうございました！！
了解しましたm(__)m

2020-07-25 02:00 UTC, SekiYukihiro reviewed
あと、今回の変更とは少し違いますが、
HAKKUTSUさんのページを見させて頂いていて
既に完成度が高いページを作られているので、
ログイン画面で出てくる「エラー文言」を日本語に変えた方が
より良いかなと思いました。

（テキストの分量的にLaravelQuestではその処理触れていませんが）
エラーメッセージを日本語に変えるのは、かなり簡単にできます！

「Laravel エラーメッセージ 日本語」などで検索して頂ければ
変更方法がすぐ出てくると思いますので、是非やって見てください。

2020-07-25 02:00 UTC, SekiYukihiro commented on resources/views/stores/index.blade.php
> +                      <option value="100">100</option>
細かい指摘で恐縮ですが、
value="5"
と書かなくても、
オプションタグの中に文字列か数字を入れていれば、valueが存在することになるので
下記の書き方でも良いのではないでしょうか？

<オプションタグ>5</オプションタグ>

2020-07-25 02:08 UTC, SekiYukihiro requested changes
ご指摘いたしました、
オプションタグのところだけ、ご修正頂ければと思います。


エラーメッセージの日本語化の方は、
ある意味別機能となるので
このブランチで変更せずに、別ブランチで対応頂いた方が良いかと思いますので
このブランチでは修正対応しなくてOKです！

2020-07-25 22:29 UTC, shunsuke-katsuyama commented on resources/views/stores/index.blade.php
> +                      <option value="100">100</option>
Seki Yukihiro さん

レビューありがとうございました。
承知いたしました。

上記の通り、修正いたします。

2020-07-25 23:50 UTC, merged