店舗詳細ページの新着商品の実装が完了しました
yuya-ishikawa-qa/hakkutsu pull request #15
Opened 2020-07-27 09:08 UTC by shunsuke-katsuyama

新着商品の実装が完了しました。

お手数をおかけいたしますが、コードレビューをお願いします。

実装内容は、店舗詳細で閲覧している店舗の新商品が表示するというものです。

2020-07-27 21:35 UTC, SekiYukihiro commented on app/Item.php
> +        return $this -> belongsTo('App\Models\Store');
App\Models\Store
このように名前空間を指定していたり、

use Illuminate\Database\Eloquent\Model;
のようにして名前空間を指定している部分がありますので

いずれかに統一するとより見やすくなるかなと思いました。

2020-07-27 21:38 UTC, SekiYukihiro commented on app/Http/Controllers/StoreDisplayController.php
> +    public function show(Request $request,$id, Store $store ,Item $item)
細かい点ですが、

public function show(Request $request, Store $store ,Item $item, $id)

このように、引数の並びを変えた方が、
意味のあるまとまりとして分かりやすいかなと思います！

2020-07-27 21:42 UTC, SekiYukihiro commented on app/Store.php
> +        return $this->hasMany('App\Models\Item');
こちらも、

return $this->hasMany(Item::class);

という形で名前空間を指定するなどした方が
統一ができるかなと思いました！

2020-07-27 21:44 UTC, SekiYukihiro requested changes
細かい表記上の点だけ、ご指摘してご返信致しました。
一度ご確認頂いて、ご訂正頂ければと思います！

お手数ですが、宜しくお願い致します。

2020-07-28 12:39 UTC, ryota100 approved these changes
実装お疲れ様です。
画面も見ましたが、OKかと思います。
よろしくお願いします。

2020-08-01 22:55 UTC, merged