店舗作成と編集機能の実装
yuya-ishikawa-qa/hakkutsu pull request #16
Opened 2020-07-29 14:30 UTC by ryota100

お世話になっております。

店舗作成と編集機能の実装ができました。

実装内容は、
ユーザーが店舗を作成できるようになり、ユーザーが作った店舗が表示されるようになりました。また、表示された店舗から店舗を編集できるようになりました。

本来は、もっと細かくプルリクをすべきかと思うのですが、大きな括りになってしまい申し訳ありません。

また、先に1件プルリクされていますので、これがマージされましたら、改めてもう一度developとマージした上で、プルリクを出したいと思っています。

お手数をおかけいたしますが、レビュー等よろしくお願いします。

2020-07-29 22:38 UTC, SekiYukihiro commented on app/Http/Controllers/StoresController.php
> -        $stores=$user->stores;
細かい点ですが、

$id = Auth::id();

このように、「=」の前後には半角スペースを入れる形で統一して頂いた方が良いかと
思います！

見やすいのと、コーディング規約で確か決まっていたと思います＾＾

2020-07-29 22:44 UTC, SekiYukihiro commented on app/Http/Controllers/StoresController.php
> +            'description' => ['required', 'string', 'max:255'],
shunさんが、下記の場所で
「フォームリクエスト」というLaravelの技術を使おうとされていたと思いますので

app/Http/Requests/StoreRequest.php 

ここでもフォームリクエストを使っても良いのではないでしょうか？

このバリデーションの記述を別ファイルに丸々移すことで可読性が上がります！

2020-07-30 01:47 UTC, SekiYukihiro commented on app/Http/Controllers/StoresController.php
> +            Storage::move($temp_path, $storage_path);
一旦保存された画像を移動させているのですね。
無駄に２個保存しないように考えられていて、素晴らしいと思います！

2020-07-30 01:52 UTC, SekiYukihiro commented on app/Http/Controllers/StoresController.php
> +            'description' => $post_data['description'],
Viewに渡すために、コントローラで一度$post_dataの配列を展開しなくても良いかなと個人的に思いました。
（ここで展開すると、行数が増えてしまい、可読性が下がりますので）

それよりは、Viewのコードが少しだけ長くなってしまうというデメリットもありますが
View上で配列を展開して表示させた方が、コントローラ上での処理が減って良いかなと思います。

2020-07-30 01:53 UTC, SekiYukihiro commented on app/Http/Controllers/StoresController.php
> +        //str_replaceメソッドで、public/をstorage/に置き換え
通常、コメントアウトするメッセージは、コードの直前に書きますね。
こんな感じです。

//str_replaceメソッドで、public/をstorage/に置き換え
$read_temp_path = str_replace('public/', 'storage/', $temp_path);

2020-07-30 02:00 UTC, SekiYukihiro requested changes
確認画面などに
セッションなどの技術をきちんと使われていて、かなり良い感じだと思います。

可読性を上げる細かい点なども含めてレビューさせて頂きましたのでご確認ください。

僕の方の環境で試したところ、店舗登録の際に同じ店名を２度使うと、
名前が重複のエラー（バリデーションエラーではなく、Laravelのエラー）が出ましたので、
重複がダメなのであれば、バリデーションで重複エラーを出すようにしましょう！

2020-08-01 17:15 UTC, ryota100 commented on app/Http/Controllers/StoresController.php
> -        $stores=$user->stores;
コーディング規約というものがあるんですね。有難うございます！
修正しました。

2020-08-01 17:19 UTC, ryota100 commented on app/Http/Controllers/StoresController.php
> +            'description' => ['required', 'string', 'max:255'],
店舗作成は、StoreRequest.php
店舗編集は、StoreupdateRequest.php
で作成しました。
一つに纏めたかったのですが、作成と編集でバリデーションの内容が少し違いましたので、分けて作成を行いました。
別に分けたことで、コントローラーが読みやすくなったように感じます。
確認よろしくお願いします。

2020-08-01 17:20 UTC, ryota100 commented on app/Http/Controllers/StoresController.php
> +            Storage::move($temp_path, $storage_path);
有難うございます！
なかなか上手く行かなかったところなので、褒めていただいて嬉しいです。

2020-08-01 17:32 UTC, ryota100 commented on app/Http/Controllers/StoresController.php
> +        //str_replaceメソッドで、public/をstorage/に置き換え
指摘ありがとうございます。
今後、そうして行きます。

2020-08-01 17:32 UTC, ryota100 commented on app/Http/Controllers/StoresController.php
> +            'description' => $post_data['description'],
64~70行の部分について、コントローラ内で展開を行わず、処理を行いました。
一度作成をしてみましたが、こうした方がいいなどあれば教えていただけると幸いです

2020-08-01 22:31 UTC, ryota100 commented
修正した後developとマージし、pushを行いました。

大変お手数ですが、確認よろしくお願いします。

2020-08-01 23:04 UTC, SekiYukihiro approved these changes
確認しました、OKです！

・フォームリクエストの活用
・コントローラで配列の展開がなくなった
・コメントアウトの位置の変更

これらで、可読性がより上がったと思います。

ただ、web.phpがコンフリクトを起こす様で、マージできないみたいなので
今の段階で、ローカルでディベロップブランチとマージしてみて、コンフリクトを解消願います！

それが完了次第、マージ致しますので、宜しくお願い致します。

2020-08-02 01:25 UTC, ryota100 commented
有難うございます！
いい勉強になりました。

web.phpについてコンフリクトの解消を行い、pushを行いました。
よろしくお願い致します。

2020-08-02 01:41 UTC, merged