Feauture/ryota/create item
yuya-ishikawa-qa/hakkutsu pull request #21
Opened 2020-08-06 15:02 UTC by ryota100

商品の作成、編集、削除機能を実装しました。
また、商品（item）に関連する消費税(tax)テーブルを作成しました。

お忙しいところお手数おかけしますが、レビューいただけると幸いです。
よろしくお願いします。

2020-08-06 23:17 UTC, SekiYukihiro commented on app/Http/Controllers/ItemsController.php
> +                'flash_message' => '出品しました',
この辺り、コードは綺麗にかけていると思うのですが、
もっと見やすくするために、
意味のある纏まりごとに改行を入れて段落を作れば
より綺麗に見た目が整って、可読性が上がると思いました✨

ご検討ください。

2020-08-06 23:21 UTC, SekiYukihiro requested changes
全体的に、コードは綺麗に書けていると思います！
良い感じですね。

可読性を上げるべきところは、詳細をコメントしましたので
ご確認ください☺️

また、developとコンフリクトが発生している様ですので
ローカルでコンフリクト解消してから、
再度プッシュ&slackでご連絡をお願い致します！

宜しくお願い致します。

2020-08-07 11:15 UTC, ryota100 commented on app/Http/Controllers/ItemsController.php
> +                'flash_message' => '出品しました',
レビュー有難うございます！
確かに詰めすぎて、意味が分からなくなってくるように感じました。
気になるところについて改行を入れました。
よろしくお願いします。

2020-08-07 11:18 UTC, ryota100 commented
ありがとうございます。
コンフリクトの解消及び、意味が通りやすいように改行の挿入を行いました。

お時間あるとき確認よろしくお願いします。

2020-08-07 23:19 UTC, SekiYukihiro commented on app/Http/Controllers/ItemsController.php
> +            ]);
次の作業もあるかと思いますので、
一旦マージさせて頂きましたが、

下記の部分でしたら、下記の例くらい細かくコメントアウトの説明文を書いて
さらに段落を分ける書き方の方が
他の人がコードを見た時に、「見やすい」と現場で喜ばれますよ〜:blush:

このブランチで再度訂正いただいても良いですが、次のブランチで作業するときでも良いと思いますので
是非変更をご検討ください！

    　　 // 完了フォーム
        public function store(Request $request)
        {
            // セッションから必要なデータを取得
            $data = $request->session()->get('data');
            $post_data = $request->session()->get('post_data');

　　　　　　　// 上記のデータを変数に代入
            $store = $data['store'];
            $temp_path = $data['temp_path'];
            $read_temp_path = $data['read_temp_path'];
            //ファイル名は$temp_pathから"public/temp/を空白で除いたもの
            $filename = str_replace('public/temp/', '', $temp_path);
            //画像を保存するパスは"public/stores_image/xxx.jpeg"
            $storage_path = 'public/stores_image/'.$filename;

　　　　　　　// dataのセッション情報を破棄
            $request->session()->forget('data');

            //Storageファサードのmoveメソッドで、第一引数->第二引数へファイルを移動
            Storage::move($temp_path, $storage_path);
            //publicをstorage/img/public/に置き換え、保存ファイルに移動
            $read_path = str_replace('public/', 'storage/', $storage_path);

　　　　　　　// データベースへの保存処理
            $item = new Item();
            $item->image_path = $read_path;
            $item->item_name = $post_data['item_name'];
            $item->status = $post_data['status'];
            $item->stock = $post_data['stock'];
            $item->price = $post_data['price'];
            $item->description = $post_data['description'];
            $item->tax_id = $post_data['tax_id'];
            $item->store_id = $store->id;
            $item->save();

            return redirect()->route('stores.management')->with([
                'flash_message' => '出品しました',
            ]);
        }

2020-08-07 23:20 UTC, SekiYukihiro approved these changes
次の作業もあるかと思いますので、
一旦マージさせて頂きましたが、

下記の部分でしたら、下記の例くらい細かくコメントアウトの説明文を書いて
さらに段落を分ける書き方の方が
他の人がコードを見た時に、「見やすい」と現場で喜ばれますよ〜:blush:

このブランチで再度訂正いただいても良いですが、次のブランチで作業するときでも良いと思いますので
是非変更をご検討ください！

    　　 // 完了フォーム
        public function store(Request $request)
        {
            // セッションから必要なデータを取得
            $data = $request->session()->get('data');
            $post_data = $request->session()->get('post_data');

　　　　　　　// 上記のデータを変数に代入
            $store = $data['store'];
            $temp_path = $data['temp_path'];
            $read_temp_path = $data['read_temp_path'];
            //ファイル名は$temp_pathから"public/temp/を空白で除いたもの
            $filename = str_replace('public/temp/', '', $temp_path);
            //画像を保存するパスは"public/stores_image/xxx.jpeg"
            $storage_path = 'public/stores_image/'.$filename;

　　　　　　　// dataのセッション情報を破棄
            $request->session()->forget('data');

            //Storageファサードのmoveメソッドで、第一引数->第二引数へファイルを移動
            Storage::move($temp_path, $storage_path);
            //publicをstorage/img/public/に置き換え、保存ファイルに移動
            $read_path = str_replace('public/', 'storage/', $storage_path);

　　　　　　　// データベースへの保存処理
            $item = new Item();
            $item->image_path = $read_path;
            $item->item_name = $post_data['item_name'];
            $item->status = $post_data['status'];
            $item->stock = $post_data['stock'];
            $item->price = $post_data['price'];
            $item->description = $post_data['description'];
            $item->tax_id = $post_data['tax_id'];
            $item->store_id = $store->id;
            $item->save();

            return redirect()->route('stores.management')->with([
                'flash_message' => '出品しました',
            ]);
        }

2020-08-07 23:21 UTC, merged