Feauture/ryota/create cart
yuya-ishikawa-qa/hakkutsu pull request #25
Opened 2020-08-13 13:41 UTC by ryota100

お世話になっております。

カート機能の実装を行いました。
・商品をカートに入れること
・カート内の商品を表示すること
・購入手続きの画面に遷移すること
の３点を実装しました。

忙しい中、お手数おかけしますが、レビューなどよろしくお願いします。

2020-08-13 22:13 UTC, SekiYukihiro commented on app/Cart.php
> +    public function add($item, $id){
よく public function store(Request $request)
のように、書かれていると思うのですが、

この部分も「$itemはItemクラスのインスタンスであることを指定する」という意味で
下記のように可読性も上がってよりいいと思いました！
型指定というPHPの技術です。

public function add(Item $item, $id){

2020-08-13 22:18 UTC, SekiYukihiro commented on app/Cart.php
> +    }
コンストラクタなどを用いて記述されていて
素晴らしいと思いました！

2020-08-13 22:34 UTC, SekiYukihiro commented on app/Cart.php
> +    public function removeItem($id){
モデルの全てのメソッドに言えることですが、
それぞれのメソッドがどんな目的で存在するメソッドなのかを
コメントアウトで記述すれば、より初見の人も読みやすくなると思いました！

例）
// カートから商品群ごと削除するメソッド
public function reduceByOne($id){

2020-08-13 22:36 UTC, SekiYukihiro requested changes
モデルに関数を記載されて切り分けられていたり、
かなりレベルが高いものを作っていただいていると思いました！

また、コメントもたくさん増やして頂いて、かなり可読性がよくなったと思いました☺️

細かい部分だけですが指摘させていただきましたので
ご確認をお願い致します。

2020-08-14 05:50 UTC, ryota100 commented on app/Cart.php
> +    public function add($item, $id){
(Request $request)をいつもよく分からず使っていました。型を指定するために変数の前に文字列を記載していると理解することができました。
有り難うございます。

2020-08-14 05:51 UTC, ryota100 commented on app/Cart.php
> +    }
見様見真似でしたが、うまく起動して安心しました。
有り難うございます。

2020-08-14 05:54 UTC, ryota100 commented on app/Cart.php
> +    public function removeItem($id){
有り難うございます。
初見で分かり辛いメソッドだと振り返ると分かりました。
修正しました。

2020-08-14 05:56 UTC, ryota100 commented
レビュー、勉強になりました。有り難うございます。

修正を行いました。
時間あるときにマージなどよろしくお願いします。

2020-08-14 06:07 UTC, SekiYukihiro approved these changes
OKです！
マージさせていただきましたので、ご確認ください。

宜しくお願い致します！

2020-08-14 06:08 UTC, merged