Feauture/ryota/create charge
yuya-ishikawa-qa/hakkutsu pull request #34
Opened 2020-08-22 05:24 UTC by ryota100

お世話になってます。

テスト決済機能及び送付先情報の登録機能を追加しました。

テスト決済については、
laravel/cashierをインストールしています。
テスト用の
クレジットカード番号：4242 4242 4242 4242
使用期限:12/21
CVC:123 
で等で利用可能です。

送付先情報の登録機能については、
住所以外の場所に郵送したい人に向けて
userテーブルに送付先郵便番号カラムと送付先住所カラムを追加しています。

忙しい中、お手数かけますが、レビュー等よろしくお願いします。

2020-08-22 08:01 UTC, SekiYukihiro commented on app/Http/Controllers/CartController.php
> +        }
細かい点ですが、
コメントアウトの記述が少し分かりにくいかもです。

//userインスタンスが送付先郵便番号を持つなら、注文情報にuserの送付先郵便番号と送付先住所を登録
if($user -> destination_postal_code){
          $order->destination_postal_code = $user->destination_postal_code;
          $order->destination = $user->destination_1.$user->destination_2.$user->destination_3;
//userインスタンスが送付先郵便番号を持たないなら、userの郵便番号と住所登録
}else{
          $order->destination_postal_code = $user->postal_code;
          $order->destination = $user->address_1.$user->address_2.$user->address_3;
}

今な感じの方が、より分かりやすいと思います！

2020-08-22 09:50 UTC, SekiYukihiro requested changes
コードは、とても綺麗に書けていると思います。

１点だけ、より可読性を上げるために、
とても細かい点ですが、修正いただけるとより良いかと思いました！

あと、先ほどまさるさんが挙げられた内容とコンフリクトしているので
その解消だけお願いします！


ただ、僕の方で上記の
.envに追記→php artisan config:cache
→laravel/cashierインストール
→マイグレーションリセット
→マイグレート再実行

を何度かやってみましたが、上手くいかなかったので
りょうたさん以外の方もこちらをマージして、stripeをやってみていただけないでしょうか？

上記だけ修正いただいたら、僕の方でdevelopにマージしますので！

僕の環境のみのエラーなら良いのですが。

※ちなみに僕は
環境の依存関係で、laravel/cashier10がインストールできなかったので
10.2.1をインストールしました。

宜しくお願い致します！

2020-08-22 11:47 UTC, ryota100 commented on app/Http/Controllers/CartController.php
> +        }
ありがとうございます。
修正しました。
可読性をあげられるよう今後の参考にします。

2020-08-22 11:51 UTC, ryota100 commented
コメントアウトとコンフリクトについて修正を行いました。

再度お手数ですが、よろしくお願いします。

2020-08-23 01:11 UTC, SekiYukihiro commented
OKです！

問題ないので、マージしました！
おつかれさまでした☺️

2020-08-23 01:11 UTC, merged